### ISSUE TITLE
drone agent on ECS

### ISSUE THREAD

**Issue by fommil** [drone-demos/drone-on-ecs#6]
hi, it looks like you're trying to set up the server on ECS but I can't see anything about the agents. Do you have any advice for running a single drone agent in ECS? I plan on creating a daemon that automatically starts/stops instances (containing tasks that contain drone-agent containers) based on the drone server's work queue.

**Comment by dcoxall** [comment]
Afraid not. This was just a very basic example and I no longer have access to AWS to test it myself.
